### ISSUE TITLE
"Removed 2 rows containing missing values (geom_segment)" message

### ISSUE THREAD

**Issue by angeloklin** [dvmlls/bdscale#5]
Hello,  
  I am using R to automate Technical Analysis and produce some OHLC bar charts for the elected securities.  
  I am still between using quantmod for charting or doing the charts myself. The main reason for not using quantmod is that I want a specific logic for when bars become red/blue.  
  I have produced some initial code for a OHLC bar chart which is good. I was going for some final touches and came across bdscale (thanks for that). But when using I am getting the above error on the segment instructions when I produce the Open and Close minor bars.  
  I wonder if it is something you could have a look, and if there would be a solution for it.  
  On the code below, the error (warning more specifically) is on the geom_segment instructions, and the effective result is that it does NOT create the Opne/Close minor bars, so it ends up with only the High/Low for the day.

Thanks & Regards,  
Angelo Klin  
professional @ angeloklin . com  

## Code
```
asx <- yahoo(ticker="^AXJO")
g <- ggplot(PLOT)
g <- g + geom_linerange(aes(x=Date, ymin=Low, ymax=High, colour=tr), size=1.5) # high/Low
g <- g + geom_segment(aes(x=Date, xend=Date-0.4, y=Open, yend=Open, colour=tr), size=1.5)   # Open
g <- g + geom_segment(aes(x=Date, xend=Date+0.4, y=Close, yend=Close, colour=tr), size=1.5) # Close
g <- g + scale_colour_manual(name="", values=c(Down="red", None="grey", Up="darkblue"))
# g <- g + scale_x_date(breaks = date_breaks("week"))
g <- g + scale_x_bd(business.dates=asx)
# g <- g + xlim(Sys.Date()-60, Sys.Date())
g <- g + theme(legend.position="none")
g <- g + labs(title=code, y="Value")
print(g)

Warning messages:
1: Removed 2 rows containing missing values (geom_segment). 
2: Removed 16 rows containing missing values (geom_segment). 
3: Removed 21 rows containing missing values (geom_segment). 
4: Removed 16 rows containing missing values (geom_segment). 
```

The data is a normal OHLC data.frame with an extra column to indicate the colour of the bar:
```
> tail(PLOT,10)
         Date  Open  High   Low Close  Volume   tr
28 2015-02-09 88.50 90.16 88.50 90.16  790200   Up
29 2015-02-10 90.55 90.84 89.14 90.00 1178000   Up
30 2015-02-11 84.00 84.80 81.48 82.95 4906500 Down
31 2015-02-12 84.00 86.14 83.62 85.54 3577300 Down
32 2015-02-13 86.04 86.85 85.21 86.54 1953000 Down
33 2015-02-16 87.48 87.68 87.06 87.37 1556100   Up
34 2015-02-17 87.00 87.37 85.95 86.59 1404900 Down
35 2015-02-18 86.77 88.65 86.59 88.50 1620200   Up
36 2015-02-19 89.90 89.93 88.50 88.67 1134900   Up
37 2015-02-23 90.00 91.23 89.73 90.26  870400   Up
```

**Comment by dvmlls** [comment]
not sure, lemme poke around a little

**Comment by dvmlls** [comment]
It issues that warning because your reference dates aren't a superset of those in your data. 

This is for some US stuff:
```
library(quantmod)
library(dplyr)
library(ggplot2)

qm2df <- function(symbol) {
  qm <- getSymbols(symbol, auto.assign=F)
  existing <- c('o', 'h', 'l', 'c', 'v', 'a')
  colnames(qm) <- existing
  df <- as.data.frame(qm)
  df$d <- index(qm)
  tbl_df(df) %>% select_(.dots=c('d', existing))
}

spy <- qm2df('SPY')
ibm <- qm2df('IBM') %>% mutate(tr=factor(c>o, c(T,F), c('Up', 'Down')))

ibm %>% ggplot(aes(x=d)) + 
  geom_linerange(aes(ymin=l, ymax=h, colour=tr)) + 
  scale_x_bd(business.dates=spy$d)

## NO WARNINGS ##
```
![image](https://cloud.githubusercontent.com/assets/7415962/6359664/ba207886-bc42-11e4-8a00-e1c8554936af.png)

When I switch to Australia, I start having problems:

```
asx <- qm2df('^AXJO')
rio <- qm2df('RIO.AX') %>% mutate(tr=factor(c>o, c(T,F), c('Up', 'Down')))

rio %>% ggplot(aes(x=d)) +
  geom_linerange(aes(ymin=l, ymax=h, colour=tr)) + 
  scale_x_bd(business.dates=spy$d)

# Warning messages:
# 1: Removed 27 rows containing missing values (geom_segment). 
# 2: Removed 48 rows containing missing values (geom_segment). 
```
![image](https://cloud.githubusercontent.com/assets/7415962/6359708/f2f3569c-bc42-11e4-8f25-ee87ebe2ac06.png)

This is because Yahoo says that [Rio Tinto](http://finance.yahoo.com/q/hp?s=RIO.AX+Historical+Prices) has a bunch of trading days that the [S&P ASX 200](http://finance.yahoo.com/q/hp?s=%5EAXJO+Historical+Prices) does not:

```
> setdiff(rio$d, asx$d) %>% as.Date
 [1] "2007-01-01" "2007-04-25" "2007-06-11" "2007-12-25" "2007-12-26" "2008-01-01"
 [7] "2008-01-28" "2008-03-21" "2008-03-24" "2008-06-09" "2008-12-25" "2009-01-01"
[13] "2009-01-26" "2009-04-10" "2009-04-13" "2010-01-26" "2010-04-02" "2010-04-05"
[19] "2010-04-26" "2010-06-14" "2010-06-16" "2010-12-27" "2011-01-03" "2011-01-26"
[25] "2011-10-10" "2011-12-26" "2011-12-27" "2012-01-02" "2012-01-16" "2012-01-26"
[31] "2012-04-06" "2012-04-09" "2012-04-11" "2012-04-25" "2012-06-11" "2012-12-25"
[37] "2012-12-26" "2013-01-01" "2013-01-28" "2013-03-29" "2013-04-01" "2013-04-25"
[43] "2013-06-10" "2013-12-25" "2013-12-26" "2014-01-01" "2014-01-27" "2014-04-18"
[49] "2014-04-21" "2014-04-25" "2014-06-09" "2014-12-25" "2014-12-26" "2015-01-01"
[55] "2015-02-24"
```

**Comment by angeloklin** [comment]
Thanks for checking on that and for digging into the data.
As this is more for the appearance anyway, I might use the time series of the security itself, instead of using the supposed always traded index of the stock exchange.

Thanks again and regards,
Angelo
