### ISSUE TITLE
dates aren't coming out properly

### ISSUE THREAD

**Issue by nealchau** [dvmlls/bdscale#7]
Scale_x_bd has been working fine for me on R 3.1, but on R 3.2.3 I believe there is an issue.  The following snippet (from stackoverflow) works on 3.1:

dts <- c(as.Date( c('2011-01-10', '2011-01-11', '2011-01-15', '2011-01-16')))
df <- data.frame(dt = dts, val = seq_along(dts)) 

ggplot(df,aes(dt,val))+geom_point()+scale_x_bd(business.dates=dts)

but now produces the following:

![scale_bd](https://cloud.githubusercontent.com/assets/3156244/13792766/c55b726c-eab0-11e5-9034-19684b05e1a4.png)

The dates on the x-axis don't go up to 1/16, but instead stop at 1/11.  

Thanks for this package!

**Comment by dvmlls** [comment]
It's working fine for me using `3.2.1`: 

```
library(ggplot2)
library(bdscale)
dts <- c(as.Date( c('2011-01-10', '2011-01-11', '2011-01-15', '2011-01-16')))
df <- data.frame(dt = dts, val = seq_along(dts)) 
ggplot(df,aes(dt,val))+geom_point()+scale_x_bd(business.dates=dts)
```

![screen shot 2016-03-15 at 4 25 50 pm](https://cloud.githubusercontent.com/assets/7415962/13792895/9aafc512-eaca-11e5-86db-1b5cf8b570e5.png)

Can you do a `sessionInfo()`?

**Comment by nealchau** [comment]
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.7 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] bdscale_1.2   ggplot2_2.1.0

loaded via a namespace (and not attached):
[1] labeling_0.3     colorspace_1.2-6 scales_0.3.0     plyr_1.8.3
[5] gtable_0.2.0     Rcpp_0.12.1      grid_3.2.3       munsell_0.4.3

**Comment by dvmlls** [comment]
Gotcha, I upgraded my R and upgraded all my packages and now I'm getting the same thing as you.

I think this has to do with the `ggplot2` upgrade from version 1.x to 2.x but let me check.

**Comment by dvmlls** [comment]
Hey @nealchau I submitted a new version to CRAN with fixes for ggplot2 v2.0. Will be available there once they approve the submission.

Until then, the code is here if you want: https://github.com/dvmlls/bdscale/releases/tag/v2.0.0

**Comment by nealchau** [comment]
Thanks a lot!  Very helpful package.

**Comment by dvmlls** [comment]
You're welcome, glad you like it.

Version 2.0.0 is on CRAN now
